name: bobwya Overlay QA

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  schedule:
    - cron: "0 6 * * *"

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bobwya/action-pkgcheck-scan@master
