name: bobwya Overlay QA

on:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: "0 6 * * 1"

jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hacking-gentoo/action-repoman@master
